on:
  issue_comment:
    types: [created]
jobs:
  action:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment'
    steps:
      - name: OpenAI Chat
        uses: fukumone/openai-chat@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GIT_TOKEN }}
          github-comment: ${{ github.event.comment.body }}
